name: Mail issue

on:
  issues:
    types: [opened, reopened]

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: install dependencies
        run: npm ci

      - name: send email
        id: sendmail
        uses: ./
        with:
          to: epicendolo@gmail.com
          from: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PWD }}

      - name: affiche la date de l'issue
        run: echo "la date de l'issue est ${{ steps.sendmail.outputs.date }}"